version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 5000:5000
  mongodb:
    image: mongo    
    ports:
      - 27017:27017